# deployer/ir_to_shell.py — the shell-script generator front-end: the
# SHARED emitters live in deployer/ir_common.py and build through the
# Emitter interface; this module provides the SHELL rendering of it
# (ShellEmitter) plus the top-level split into the two script families
# `build_scripts()` returns — the cluster-wide ovn-nbctl script (run
# once, from whichever chassis reaches the shared NB DB) and one
# per-host OVS/netns script (run on the host itself) — for the
# requested action. See ir_common.py's own header for the full design
# rationale.

from __future__ import annotations

import shlex

from protocol import generated as pt

from .ir_common import Action, Emitter, _emit_cluster_body, _emit_host_script

# re-exported so `from deployer.ir_to_shell import generate_python_deployer`
# (and the tests' `mod.generate_python_deployer`) keeps working without
# caring which front-end module owns it (2026-08-19).
from .ir_to_python import generate_python_deployer  # noqa: E402  (re-export)

__all__ = [
    "Action",
    "build_scripts",
    "generate_python_deployer",
]


class ShellEmitter(Emitter):
    """The shell rendering of the shared emitter interface: a command
    becomes a shlex-joined line, a file append becomes a
    `cat > path << 'EOF'` heredoc (whose body always ends in a newline,
    matching the Python backend's write_file()). `action` (create/
    delete) is carried on the emitter — the SAME parameter every
    ir_common emitter branches on — so a create and its reverse (delete)
    live in one emitter function."""

    def __init__(self, action: Action) -> None:
        super().__init__(action)

    def sh(self, argv: list[str], background: bool = False) -> None:
        self.lines.append(shlex.join(argv) + (" &" if background else ""))

    def append(self, path: str, content: str) -> None:
        self.lines.append(f"cat > {path} << 'OVN'")
        self.lines.append(content)
        self.lines.append("OVN")


def _cluster_script(nodes: list[pt.Model], action: Action) -> str:
    emit = ShellEmitter(action)
    emit.raw("#!/bin/sh")
    emit.raw(f"# Cluster-wide OVN topology (ovn-nbctl only, action={action}) —")
    emit.raw("# run ONCE, from whichever chassis reaches the shared NB DB")
    emit.raw("# (typically the central one). Generated by")
    emit.raw("# deployer/ir_to_shell.py. Deciding WHICH nodes actually need")
    emit.raw("# this action (i.e. diffing against live state) is the")
    emit.raw("# reconciler's job, not this script's — this is one blunt")
    emit.raw(f"# {action}-everything pass.")
    # A delete pass runs against whatever state IS there — a
    # missing object is expected, not fatal — so it drops `-e` and
    # keeps going past any failing command (2026-08-18). Create
    # keeps `set -eu`: a failed create really is an error.
    emit.raw("set -u" if action == "delete" else "set -eu")
    emit.blank()
    _emit_cluster_body(nodes, emit)
    return "\n".join(emit.lines)


def _host_script(node: pt.InfraHostNode, nodes: list[pt.Model], action: Action) -> str:
    host_name = node.key.host
    emit = ShellEmitter(action)
    emit.raw("#!/bin/sh")
    emit.raw(f"# Host-local OVS/chassis registration for {host_name}")
    emit.raw(f"# (action={action}) — run ON this host directly, not against")
    emit.raw("# the cluster script's target. Generated by")
    emit.raw("# deployer/ir_to_shell.py.")
    # Same delete-vs-create rule as _cluster_script: a delete
    # pass must not abort on a missing object (2026-08-18).
    emit.raw("set -u" if action == "delete" else "set -eu")
    emit.blank()
    _emit_host_script(node, nodes, emit)
    return "\n".join(emit.lines)


def build_scripts(nodes: list[pt.Model], action: Action) -> tuple[str, dict[str, str]]:
    if action not in ("create", "delete"):
        raise ValueError(f'action must be "create" or "delete", got {action!r}')

    host_scripts = {
        node.key.host: _host_script(node, nodes, action)
        for node in nodes
        if node.kind == "infra.host"
    }
    return _cluster_script(nodes, action), host_scripts
