# deployer/ir_to_python.py — the all-in-one Python deployer generator:
# every shell emitter lives in deployer/ir_common.py (shared with the
# shell-script generator, deployer/ir_to_shell.py); this module embeds
# that generator's exact blocks (cluster + per-host, create + delete,
# `set` envelope included) into ONE self-contained Python file that
# picks what to run at runtime (2026-08-19):
#   --action create|delete   (default create; create aborts on the first
#                             failed command, delete warns and continues)
#   --cluster                only the cluster-wide ovn-nbctl pass
#   --host NAME              only that host's pass
#   --verbose                echo every command before running it
# With neither --cluster nor --host, everything runs: cluster first,
# then every host in declaration order. The generated file executes each
# command itself (line-by-line, colored log) so failures are visible —
# the block's own `set` envelope lines are skipped, not executed.
# python3 is required on every target host (2026-08-19, confirmed).

from __future__ import annotations

from protocol import generated as pt

from .ir_common import _emit_cluster_script, _emit_host_script


def _py_str(s: str) -> str:
    """Embed `s` verbatim as a triple-quoted Python string literal."""
    return '"""' + s.replace("\\", "\\\\").replace('"""', '\\"\\"\\"') + '"""'


_GENERATED_RUNTIME = r"""#!/usr/bin/env python3
# Generated by ovn-fabric deployer/ir_to_python.py — DO NOT EDIT.
#
# One file for every pass the generator knows: the cluster-wide ovn-nbctl
# action (run once, from whichever chassis reaches the shared NB DB) and
# each per-host OVS/netns action (run on the host itself), for both
# create and delete. Pick what to run with --action / --cluster / --host;
# with neither --cluster nor --host, everything runs (cluster first, then
# each host in declaration order).
#
# Each block is the exact shell the shell generator emits (its `set`
# envelope included). Python executes it command-by-command so it can log
# every command (--verbose, colored) and decide the error policy: create
# aborts on the first failure, delete warns and keeps going.

import argparse
import shlex
import subprocess
import sys

GREEN = "\033[32m"
YELLOW = "\033[33m"
RED = "\033[31m"
RESET = "\033[0m"


def run_block(label: str, block: str, verbose: bool, abort_on_error: bool) -> None:
    for raw_line in block.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or line.startswith("set -"):
            continue
        if verbose:
            print(f"{GREEN}{label}$ {line}{RESET}")
        try:
            proc = subprocess.run(shlex.split(line))
        except OSError as exc:
            # e.g. the binary isn't installed on this host — same
            # "command failed" policy, not a crash (2026-08-19).
            detail = f" ({exc.strerror})" if exc.strerror else ""
            if abort_on_error:
                print(f"{RED}error: cannot run in {label}{detail}: {line}{RESET}", file=sys.stderr)
                sys.exit(127)
            print(f"{YELLOW}warning: cannot run in {label}{detail}: {line}{RESET}", file=sys.stderr)
            continue
        if proc.returncode == 0:
            continue
        if abort_on_error:
            print(f"{RED}error: failed in {label}: {line}{RESET}", file=sys.stderr)
            sys.exit(proc.returncode)
        print(f"{YELLOW}warning: failed in {label}: {line}{RESET}", file=sys.stderr)


CLUSTER_CREATE = __CLUSTER_CREATE__
CLUSTER_DELETE = __CLUSTER_DELETE__

HOSTS = {
__HOSTS__
}


def main() -> int:
    parser = argparse.ArgumentParser(description="ovn-fabric generated deployer")
    parser.add_argument(
        "--action",
        choices=["create", "delete"],
        default="create",
        help="create (default) aborts on the first failed command; delete warns and continues",
    )
    parser.add_argument(
        "--cluster",
        action="store_true",
        help="run only the cluster-wide ovn-nbctl pass",
    )
    parser.add_argument("--host", metavar="NAME", help="run only this host's pass")
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="echo every command before running it",
    )
    args = parser.parse_args()
    abort_on_error = args.action == "create"

    if args.host is not None:
        if args.host not in HOSTS:
            print(
                f"{RED}error: unknown host {args.host!r}; known hosts: {', '.join(HOSTS)}{RESET}",
                file=sys.stderr,
            )
            return 2
        targets = [(f"host:{args.host}", HOSTS[args.host][args.action])]
    else:
        cluster = CLUSTER_CREATE if args.action == "create" else CLUSTER_DELETE
        targets = [("cluster", cluster)]
        if not args.cluster:
            targets.extend((f"host:{name}", HOSTS[name][args.action]) for name in HOSTS)

    for label, block in targets:
        run_block(label, block, args.verbose, abort_on_error)
    return 0


if __name__ == "__main__":
    sys.exit(main())
"""


def generate_python_deployer(nodes: list[pt.Model]) -> str:
    """The all-in-one Python deployer: every action of every pass,
    embedded shell blocks + the runtime above (2026-08-19)."""
    host_entries = ",\n".join(
        f"    {name!r}: {{\n"
        f'        "create": {_py_str(_emit_host_script(node, nodes, "create"))},\n'
        f'        "delete": {_py_str(_emit_host_script(node, nodes, "delete"))},\n'
        "    }"
        for node in nodes
        if node.kind == "infra.host"
        for name in [node.key.host]
    )
    return (
        _GENERATED_RUNTIME.replace(
            "__CLUSTER_CREATE__", _py_str(_emit_cluster_script(nodes, "create"))
        )
        .replace("__CLUSTER_DELETE__", _py_str(_emit_cluster_script(nodes, "delete")))
        .replace("__HOSTS__", host_entries)
    )
