// src/protocol.ts — the protocol of ovn-fabric: the one schema both
// languages agree on for the desired-state IR that crosses the
// TypeScript/Python boundary (toIR(), src/ir.ts, producing JSON ->
// deployer/, consuming it). This is the stabilizing factor for that
// boundary — the two sides are built, tested, and deployed
// independently, so nothing else guarantees a newer TS generator's IR
// shape still matches what an older Python deployer bundle expects.
//
// One ArkType schema per kind, unioned into IRNode — matches ADR 0002
// § Decision, point 4 exactly (already the plan recorded there for the
// reconciler's live-state side; this is the same mechanism applied to
// toIR()'s desired-state side).
//
// `key`/`data` are each their OWN named schema (InfraHostKey,
// InfraHostData, ...), not inlined into their Node schema — buildJsonSchema()
// below emits every one of these as its own named entry in the JSON
// Schema's $defs, referenced by $ref from its Node. A plain inlined
// shape has no name of its own in JSON Schema, so datamodel-codegen
// falls back to auto-numbering (Data, Data1, Data2, ...) — fragile:
// that numbering depends on definition order and shifts if a kind is
// ever added or reordered, silently breaking any hand-written Python
// that references e.g. `Data1` by name. Named $defs make every
// generated class name stable regardless of how many kinds exist or
// what order they're declared in.
//
// This schema is consumed two ways, never validated against directly
// at runtime on either side:
//   1. `deno run -A src/cli.ts generate-pytypes` calls buildJsonSchema()
//      and writes protocol/ir-nodes.schema.json.
//   2. `datamodel-codegen` (build-time-only, generator hardware only,
//      never ships to a router) turns that JSON Schema into plain
//      stdlib Python dataclasses (protocol/generated.py) — see that
//      file's own header for why a required-argument TypeError is the
//      intentional, sufficient failure mode for version skew, not a
//      hand-written validator.
//
// Only the kinds toIR() actually produces today (src/ir.ts) — ovn.ls's
// `interfaces[].iface` stays `unknown` here rather than modeling the
// full InterfaceKind union: that shape lives entirely within the
// TypeScript side (ovn-fabric's own config authoring), the Python side
// never inspects it structurally (deployer/ir_to_shell.py only reads
// `.kind`/named fields it recognizes, see _iface_real_name), so
// pinning its exact shape into the cross-language protocol would add a
// second place to keep in sync for no real benefit yet.

import { type } from "arktype";

export const InfraHostKey = type({ host: "string" });
export const HostOs = type({ name: "string", version: "string" });
export const InfraHostData = type({
  connectAddress: "string",
  "ovnRole?": "'central'|'chassis'",
  "encapIp?": "string",
  // Always resolved (assume Ubuntu when the config leaves it unset,
  // 2026-08-23) — the deployer installs the dependencies in this OS's
  // package form. No deinstall ever.
  os: HostOs,
  // The OS packages/requirements this host needs (ovs/ovn, iproute2/
  // iptables, dhcpcd/dhclient, wireguard-tools, zerotier, docker).
  "dependencies?": "string[]",
});
export const InfraHostNode = type({
  id: "string",
  kind: "'infra.host'",
  key: InfraHostKey,
  data: InfraHostData,
});

// `iface` carries `shortName` (the real, IFNAMSIZ-safe OVS bridge name
// for this domain, src/ir.ts's own shortIfaceName() — always resolved
// by the time toIR() emits it, never computed translator-side) among
// its own fields — `iface` stays `unknown` here regardless (see this
// file's header), so shortName isn't separately named in the protocol.
export const OvnLsInterface = type({ host: "string", iface: "unknown" });
export const OvnLsKey = type({ name: "string" });
export const OvnLsData = type({
  interfaces: OvnLsInterface.array(),
});
export const OvnLsNode = type({
  id: "string",
  kind: "'ovn.ls'",
  key: OvnLsKey,
  data: OvnLsData,
});

export const OvnLrpKey = type({
  ovnrouter: "string",
  side: "'left'|'right'",
});
export const OvnLrpData = type({
  // `ls:<name>` — the referenced ovn.ls node's own id, not the bare
  // domain name (src/ir.ts's own routerEndpointToIR — every cross-node
  // reference in the IR is an id, confirmed live 2026-08-12).
  l2Segment: "string",
  addresses: "string[]",
  // Always resolved by the time toIR() emits it (src/ir.ts's own
  // resolveMac) — not optional here, so a JSON file missing it (e.g.
  // generated by a stale pre-mac-resolution build) fails protocol
  // validation instead of reaching the deployer at all.
  mac: "string",
  // `host:<name>` — the referenced infra.host node's own id, same
  // reasoning as l2Segment above.
  "gatewayChassis?": "string",
  // Already-resolved ipv6_ra_configs key/value pairs (src/ir.ts's own
  // resolveIpv6RaConfigs, from RouterEndpoint.services — see
  // RouterEndpointService, types.ts) — undefined means no RA service
  // was declared, not "set zero keys."
  "ipv6RaConfigs?": { "[string]": "string" },
});
export const OvnLrpNode = type({
  id: "string",
  kind: "'ovn.lrp'",
  key: OvnLrpKey,
  data: OvnLrpData,
});

// ipv4.route / ipv6.route: computed by src/ir.ts's computeRoutes() and
// computeInterconnectRoutes() from net.routingDomain() declarations
// (see RoutingDomain, types.ts) — one node per router per resolved
// route. Same key/data shape for both families (only `kind` differs),
// so one pair of schemas covers both rather than duplicating an
// identical shape twice.
export const RouteKey = type({ ovnrouter: "string", prefix: "string" });
// `domain`: the net.routingDomain() name that produced this route —
// every route belongs to exactly one domain (interconnect routes only
// exist between a domain's own participants, confirmed live
// 2026-08-12; see src/ir.ts's computeInterconnectRoutes). Lets the
// deployer group a router's routes into labeled blocks instead of one
// flat, unlabeled dump.
export const RouteData = type({
  nexthop: "string",
  masq: "boolean",
  domain: "string",
});
export const Ipv4RouteNode = type({
  id: "string",
  kind: "'ipv4.route'",
  key: RouteKey,
  data: RouteData,
});
export const Ipv6RouteNode = type({
  id: "string",
  kind: "'ipv6.route'",
  key: RouteKey,
  data: RouteData,
});

// kernel.router: THREE nodes per KernelRouter (types.ts) — a real Linux
// netns, not an OVN kind at all (src/ir.ts's kernelRouterToIR/
// kernelRouterSideToIR). `side` absent means the router-level node
// (`key: {name}` only) — just the host reference (`host:<name>`, the
// referenced infra.host node's own id, same as OvnLrpData.
// gatewayChassis); `side` present means one of the two per-side nodes
// (same shape convention as ovn.lrp: `key: {name, side}`, `data` fields
// flat), which still repeat `host` too — both live in the same netns,
// and the router-level node is additive, not a replacement for that.
// `ipaddrs`/`routes` are only present on a per-side node: `ipaddrs` is
// already a fully resolved address list, `routes` only the entries with
// a real nexthop to apply (a route with none means "handled elsewhere,"
// e.g. real-world RA/DHCP — see kernelRouterSideToIR's own comment) —
// no real iface binding yet (deliberately deferred, its own next step),
// so the deployer's job for this kind is "create the netns on `host`,
// then a dummy device per side to carry these addresses/routes."
export const KernelRouterKey = type({
  name: "string",
  "side?": "'left'|'right'",
});
export const KernelRouterRoute = type({ dst: "string", via: "string" });
// KernelApp — a fully-resolved kernel-netns application (types.ts): the
// `kernel.app.*` service kinds resolved at declaration time. An `or`
// union DISCRIMINATED on `kind` (2026-08-23) — each variant carries
// exactly its own fields, so a docker app can't accidentally gain a
// `style` and a dhcp-client can't carry `image` (the flat-schema shape
// before this couldn't express that).
export const WireguardPeerConfig = type({
  publicKey: "string",
  endpoint: "string",
  allowedIps: "string",
  "persistentKeepalive?": "number",
});
export const WireguardAppConfig = type({
  privateKey: "string",
  address: "string",
  "listenPort?": "number",
  "dns?": "string",
  peer: WireguardPeerConfig,
});
export const DhcpClientApp = type({
  kind: "'dhcp-client'",
  style: "'dhclient'|'dhcpcd'",
});
export const WireguardApp = type({
  kind: "'wireguard'",
  ifaceName: "string",
  config: WireguardAppConfig,
  masq: "('ipv4'|'ipv6')[]",
});
export const ZerotierApp = type({
  kind: "'zerotier'",
  networkId: "string",
  instanceDir: "string",
  masq: "('ipv4'|'ipv6')[]",
});
export const DockerApp = type({
  kind: "'docker'",
  image: "string",
  name: "string",
  "cmd?": "string[]",
  "ip?": "string",
  "routerIp?": "string",
  "vethName?": "string",
});
export const KernelApp = DhcpClientApp.or(WireguardApp).or(ZerotierApp).or(
  DockerApp,
);
export const KernelRouterData = type({
  host: "string",
  "ipaddrs?": "string[]",
  "routes?": KernelRouterRoute.array(),
  // Real physical attachment(s) for this side — same {host, iface}
  // shape as OvnLsInterface (iface stays `unknown`, structurally
  // unmodeled — src/ir.ts's kernelRouterSideToIR emits the raw
  // InterfaceKind object; see OvnLsInterface's own comment above).
  // Present on the `right` side node today (2026-08-18 — the OVN-side
  // endpoint keeps its own copy so the transit domain's bridge binding
  // survives, see buildKernelRouterEndpoint); absent = bind to a dummy
  // device.
  "ifaces?": OvnLsInterface.array(),
  // The `security.group` node's name (`masq-<router>` for the masq
  // shortcut) attached to THIS side's interface (right side only in
  // practice) — the attachment point for the rules that group carries;
  // see SecurityGroupKey below.
  "securityGroup?": "string",
  // The tunnel router's UPSTREAM peer address(es) — the OTHER end of the
  // upstream veth (right side only; tunnelRouterEndpoint, define.ts). The
  // deployer brings that root-side peer leg up and assigns it these
  // addresses so the netns's default route (via the peer) has a live
  // gateway (2026-08-23).
  "upstreamPeerAddrs?": "string[]",
  // Applications running inside the netns on this side's real interface
  // (right side only in practice — src/ir.ts's kernelRouterSideToIR,
  // from KernelApp, types.ts). The deployer turns each into its
  // `ip netns exec` service script and MUST stop/release it on delete.
  "apps?": KernelApp.array(),
});
export const KernelRouterNode = type({
  id: "string",
  kind: "'kernel.router'",
  key: KernelRouterKey,
  data: KernelRouterData,
});

// security.group: an IMPLEMENTATION-ABSTRACT named set of rules
// (src/ir.ts's securityGroupToIR, from KernelRouterSide.services/
// securityGroup, types.ts). The name is just a label (derived from the
// owning router today, `sg-<router>`, in buildKernelRouterEndpoint,
// define.ts — never author-chosen); the ATTACHMENT lives on whichever
// node carries a `securityGroup` reference (today a kernel.router side
// node, later an ovn.lrp or anything else). Rules use a generic
// vocabulary (kind `masq` = masquerade, family = address family) that
// each implementation maps to its own concrete command; future kernel
// services (docker containers, wireguard) extend this same rules list.
export const SecurityGroupRule = type({
  family: "'ipv4'|'ipv6'",
  kind: "'masq'",
});
export const SecurityGroupKey = type({ name: "string" });
export const SecurityGroupData = type({
  rules: SecurityGroupRule.array(),
});
export const SecurityGroupNode = type({
  id: "string",
  kind: "'security.group'",
  key: SecurityGroupKey,
  data: SecurityGroupData,
});

export const IRNode = InfraHostNode.or(OvnLsNode).or(OvnLrpNode).or(
  Ipv4RouteNode,
).or(
  Ipv6RouteNode,
).or(
  KernelRouterNode,
).or(
  SecurityGroupNode,
);

// Every node kind's envelope has the exact same shape (id: string,
// kind: const, key: $ref, data: $ref) — generated once here instead of
// by hand per kind, so a fifth field added to the envelope someday only
// needs changing in one place.
function nodeSchema(kind: string, keyDef: string, dataDef: string) {
  return {
    type: "object",
    properties: {
      id: { type: "string" },
      kind: { const: kind },
      key: { "$ref": `#/$defs/${keyDef}` },
      data: { "$ref": `#/$defs/${dataDef}` },
    },
    required: ["id", "kind", "key", "data"],
  };
}

/** The full protocol as JSON Schema (draft 2020-12), named $defs
 * throughout — see this file's header comment for why. */
export function buildJsonSchema(): Record<string, unknown> {
  const defs: Record<string, unknown> = {
    InfraHostKey: InfraHostKey.toJsonSchema(),
    InfraHostData: InfraHostData.toJsonSchema(),
    InfraHostNode: nodeSchema("infra.host", "InfraHostKey", "InfraHostData"),
    OvnLsKey: OvnLsKey.toJsonSchema(),
    OvnLsData: OvnLsData.toJsonSchema(),
    OvnLsNode: nodeSchema("ovn.ls", "OvnLsKey", "OvnLsData"),
    OvnLrpKey: OvnLrpKey.toJsonSchema(),
    OvnLrpData: OvnLrpData.toJsonSchema(),
    OvnLrpNode: nodeSchema("ovn.lrp", "OvnLrpKey", "OvnLrpData"),
    RouteKey: RouteKey.toJsonSchema(),
    RouteData: RouteData.toJsonSchema(),
    Ipv4RouteNode: nodeSchema("ipv4.route", "RouteKey", "RouteData"),
    Ipv6RouteNode: nodeSchema("ipv6.route", "RouteKey", "RouteData"),
    KernelRouterKey: KernelRouterKey.toJsonSchema(),
    KernelRouterData: KernelRouterData.toJsonSchema(),
    KernelRouterNode: nodeSchema(
      "kernel.router",
      "KernelRouterKey",
      "KernelRouterData",
    ),
    SecurityGroupKey: SecurityGroupKey.toJsonSchema(),
    SecurityGroupData: SecurityGroupData.toJsonSchema(),
    SecurityGroupNode: nodeSchema(
      "security.group",
      "SecurityGroupKey",
      "SecurityGroupData",
    ),
  };
  return {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$defs": defs,
    "oneOf": [
      "InfraHostNode",
      "OvnLsNode",
      "OvnLrpNode",
      "Ipv4RouteNode",
      "Ipv6RouteNode",
      "KernelRouterNode",
      "SecurityGroupNode",
    ].map((
      name,
    ) => ({
      "$ref": `#/$defs/${name}`,
    })),
  };
}
