// src/protocol.ts — the protocol of ovn-fabric: the one schema both
// languages agree on for the desired-state IR that crosses the
// TypeScript/Python boundary (toIR(), src/ir.ts, producing JSON ->
// deployer/, consuming it). This is the stabilizing factor for that
// boundary — the two sides are built, tested, and deployed
// independently, so nothing else guarantees a newer TS generator's IR
// shape still matches what an older Python deployer bundle expects.
//
// One ArkType schema per kind, unioned into IRNode — matches ADR 0002
// § Decision, point 4 exactly (already the plan recorded there for the
// reconciler's live-state side; this is the same mechanism applied to
// toIR()'s desired-state side).
//
// `key`/`data` are each their OWN named schema (InfraHostKey,
// InfraHostData, ...), not inlined into their Node schema — buildJsonSchema()
// below emits every one of these as its own named entry in the JSON
// Schema's $defs, referenced by $ref from its Node. A plain inlined
// shape has no name of its own in JSON Schema, so datamodel-codegen
// falls back to auto-numbering (Data, Data1, Data2, ...) — fragile:
// that numbering depends on definition order and shifts if a kind is
// ever added or reordered, silently breaking any hand-written Python
// that references e.g. `Data1` by name. Named $defs make every
// generated class name stable regardless of how many kinds exist or
// what order they're declared in.
//
// This schema is consumed two ways, never validated against directly
// at runtime on either side:
//   1. `deno run -A src/cli.ts generate-pytypes` calls buildJsonSchema()
//      and writes protocol/ir-nodes.schema.json.
//   2. `datamodel-codegen` (build-time-only, generator hardware only,
//      never ships to a router) turns that JSON Schema into plain
//      stdlib Python dataclasses (protocol/generated.py) — see that
//      file's own header for why a required-argument TypeError is the
//      intentional, sufficient failure mode for version skew, not a
//      hand-written validator.
//
// Only the kinds toIR() actually produces today (src/ir.ts) — ovn.ls's
// `interfaces[].iface` stays `unknown` here rather than modeling the
// full InterfaceKind union: that shape lives entirely within the
// TypeScript side (ovn-fabric's own config authoring), the Python side
// never inspects it structurally (deployer/ir_to_shell.py only reads
// `.kind`/named fields it recognizes, see _iface_real_name), so
// pinning its exact shape into the cross-language protocol would add a
// second place to keep in sync for no real benefit yet.

import { type } from "arktype";

export const InfraHostKey = type({ host: "string" });
export const InfraHostData = type({
  connectAddress: "string",
  "ovnRole?": "'central'|'chassis'",
  "encapIp?": "string",
});
export const InfraHostNode = type({
  id: "string",
  kind: "'infra.host'",
  key: InfraHostKey,
  data: InfraHostData,
});

export const OvnLsInterface = type({ host: "string", iface: "unknown" });
export const OvnLsKey = type({ name: "string" });
export const OvnLsData = type({ interfaces: OvnLsInterface.array() });
export const OvnLsNode = type({
  id: "string",
  kind: "'ovn.ls'",
  key: OvnLsKey,
  data: OvnLsData,
});

export const OvnLrpKey = type({ router: "string", side: "'left'|'right'" });
export const OvnLrpData = type({
  l2Segment: "string",
  addresses: "string[]",
  // Always resolved by the time toIR() emits it (src/ir.ts's own
  // resolveMac) — not optional here, so a JSON file missing it (e.g.
  // generated by a stale pre-mac-resolution build) fails protocol
  // validation instead of reaching the deployer at all.
  mac: "string",
  "gatewayChassis?": "string",
});
export const OvnLrpNode = type({
  id: "string",
  kind: "'ovn.lrp'",
  key: OvnLrpKey,
  data: OvnLrpData,
});

export const IRNode = InfraHostNode.or(OvnLsNode).or(OvnLrpNode);

// Every node kind's envelope has the exact same shape (id: string,
// kind: const, key: $ref, data: $ref) — generated once here instead of
// by hand per kind, so a fifth field added to the envelope someday only
// needs changing in one place.
function nodeSchema(kind: string, keyDef: string, dataDef: string) {
  return {
    type: "object",
    properties: {
      id: { type: "string" },
      kind: { const: kind },
      key: { "$ref": `#/$defs/${keyDef}` },
      data: { "$ref": `#/$defs/${dataDef}` },
    },
    required: ["id", "kind", "key", "data"],
  };
}

/** The full protocol as JSON Schema (draft 2020-12), named $defs
 * throughout — see this file's header comment for why. */
export function buildJsonSchema(): Record<string, unknown> {
  const defs: Record<string, unknown> = {
    InfraHostKey: InfraHostKey.toJsonSchema(),
    InfraHostData: InfraHostData.toJsonSchema(),
    InfraHostNode: nodeSchema("infra.host", "InfraHostKey", "InfraHostData"),
    OvnLsKey: OvnLsKey.toJsonSchema(),
    OvnLsData: OvnLsData.toJsonSchema(),
    OvnLsNode: nodeSchema("ovn.ls", "OvnLsKey", "OvnLsData"),
    OvnLrpKey: OvnLrpKey.toJsonSchema(),
    OvnLrpData: OvnLrpData.toJsonSchema(),
    OvnLrpNode: nodeSchema("ovn.lrp", "OvnLrpKey", "OvnLrpData"),
  };
  return {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$defs": defs,
    "oneOf": ["InfraHostNode", "OvnLsNode", "OvnLrpNode"].map((name) => ({
      "$ref": `#/$defs/${name}`,
    })),
  };
}
